### ISSUE TITLE
Make NPU compatible with GreaseMonkey 4

### ISSUE THREAD

**Issue by tacsipacsi** [solymosi/npu#19]
GreaseMonkey 4 has some [breaking changes](https://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html), which need script fixes to become compatible. The old methods should be kept, too, to keep compatibility with Tampermonkey.

**Comment by solymosi** [comment]
Hmm... you are right. Can you pls review #20 and check if I've missed something?

**Comment by tacsipacsi** [comment]
I think after adding the polyfill, you have to rewrite the code – it’s for backward-compatibility, not forward.

**Comment by solymosi** [comment]
Whoops, I misread the post about the API upgrade. Should be fixed now, thanks for catching it (I'm still on Firefox 52 ESR because of a few other legacy plugins, so I couldn't test on GM4).

**Comment by tacsipacsi** [comment]
Sorry for the late response, I looked through the whole code to understand it and find potential issues. The only thing I caught it that `GM_xmlhttpRequest` is now called `GM.xmlHttpRequest` (with a capital H). Anyway, I think you should at least let people know about tracking – I know it’s as anonymous as it can be, but (I think) for any form of data collection a privacy policy is required by law, and also it’s obvious now that even if you intend it to be completely anonymous, it can’t be in case of hacker attacks.
(P. S. You can download [Firefox Developer Edition](https://www.mozilla.org/hu/firefox/developer/) beside Firefox ESR, which is already at 58.0 so that you can test the WebExtension version yourself.)

**Comment by solymosi** [comment]
@tacsipacsi Thanks for the review, I fixed the issue and tested the script on FF58 Developer Edition. 

I have added a simple privacy notice to the homepage. You are absolutely right that this should be made more explicit, and I was meaning to add a note when I first implemented the stat submission, but just never got around to actually doing it.

Btw, here are the latest numbers. Looks like 20,000+ unique stat codes (~ new script installations) have been reported since I reset the stats last year:

![image](https://user-images.githubusercontent.com/199790/33247502-6f7b9c5a-d316-11e7-97ee-81f63c767540.png)
