### ISSUE TITLE
Store latest supported Neptun version in a script variable, show a bit of warning on login page if higher

### ISSUE THREAD

**Issue by whisperity** [solymosi/npu#30]
Example ELTE: ![image](https://user-images.githubusercontent.com/1969470/40652071-8831e482-6337-11e8-9533-1eb22f20e194.png)

BME: ![image](https://user-images.githubusercontent.com/1969470/40652081-8cb18c6a-6337-11e8-90d6-1650689b3d38.png)

**Comment by solymosi** [comment]
I like this idea, it also shouldn't be very hard to implement :+1:

The wording of the warning message is crucial, because we need it to be actionable. We can't just say, "this version is not guaranteed to be compatible" because the average user won't know what to do about that. Instead, we should instruct the user to check the NPU homepage for updates, and leave a comment about the new Neptun version if there aren't any updates. We also need to tell them that they might need to temporarily disable the script if it breaks the operation of Neptun in a severe way.

If v2.0 ever gets implemented (see https://github.com/solymosi/npu/issues/12), we can go even further and introduce the ability to mark the Neptun version compatibility of individual modules. That way we could have multiple modules implementing the same feature, each with a different compatibility setting, and the system would use the one that matches the Neptun version of the university in question.

**Comment by whisperity** [comment]
It seems the versioning scheme officialy has changed.

ELTE: 
![image](https://user-images.githubusercontent.com/1969470/87290745-aa880680-c4fe-11ea-9ff7-2c3ef09d0180.png)

BME: 
![image](https://user-images.githubusercontent.com/1969470/87290759-ad82f700-c4fe-11ea-92a9-a402c84d7702.png)

**Comment by whisperity** [comment]
Aaaand shit... the new ELTE homepage basically side-steps the Neptun log-in logic, and there isn't any page anymore where the version string is available.

BME is still going strong, and they are using: *Verzió: 2020.3.33 (2021. 02. 02.)*

**Comment by solymosi** [comment]
@whisperity Yeah, I also noticed 😕

In general I'm not convinced that such a warning would bring too much benefit. It would mean that we'd have to keep re-testing the script on each new version of Neptun and bumping the version number in the script, even though major changes that would break the script are very rare: in August the script will be 10 years old and e.g. most of the original course registration UI enhancements have survived just fine ever since.

**Comment by whisperity** [comment]
Yeah, let's scrap this... Only one thing broke once, the already taken exams page, or something like that, I remember fixing a few years ago.
