### ISSUE TITLE
JScript compilation error code 800A03F14

### ISSUE THREAD

**Issue by GellertGit** [solymosi/npu#50]
Dear Mate, 

Any suggestion on this? Got it on all computers I tried recently. Even tried with C+P to tampermonkey and run from there - didn't work.
![Screenshot 2020-10-10 143102](https://user-images.githubusercontent.com/28756751/95655106-f72eae00-0afc-11eb-9670-5bcae70d8c22.png)

**Comment by solymosi** [comment]
You should not be running the script directly. Please follow the install instructions in the README.

**Comment by GellertGit** [comment]
Máté, I followed, however TM is added as an extension and yet nothing happens when I download the .js :( that is why i posted the 'issue'

**Comment by solymosi** [comment]
Which browser are you using?

**Comment by GellertGit** [comment]
chrome

**Comment by GellertGit** [comment]
do I have to add it as a new script? if it wont work automatically?

**Comment by GellertGit** [comment]
I tried install this link into TM: https://github.com/solymosi/npu.git and it said invalid UserScript :(

**Comment by solymosi** [comment]
I have just tried installing Tampermonkey and the script in a new Chrome profile and it worked as expected. Not sure what the issue is in your case.

> I tried install this link into TM: https://github.com/solymosi/npu.git and it said invalid UserScript :(

Ah, that's the issue then. Don't use this:

![image](https://user-images.githubusercontent.com/199790/95655956-48459e80-0b0b-11eb-93ad-80334a85db00.png)

Use this instead:

![image](https://user-images.githubusercontent.com/199790/95655964-53003380-0b0b-11eb-902a-6189827be397.png)

**Comment by GellertGit** [comment]
Sorry for bothering - something went wrong in my TM - killed it and reinstalled - now all ok. THANKS
