### ISSUE TITLE
Auto skip ELTE "news" section.

### ISSUE THREAD

**Issue by Kokan** [solymosi/npu#51]
According to this video: https://www.youtube.com/watch?v=C_bvX1CvgNM&list=PLm3AdVwMMCqwkassnBLieCx7LGM0buK4Z&index=1
After today update elte's neptun site going to have a 
* different login page
* a news site as default page after login, which requires an extra step to reach the actual neptun

Would it be acceptable adding elte specific changes to the NPU project ?
(I have access to ELTE Neptun, and can do test if needed)

**Comment by whisperity** [comment]
Let's wait until it's rolled out and the day zero patches are in to see how broken the entire ordeal will get.

**Comment by whisperity** [comment]
NPU still works once you're through the login page. The original login page is NOT available anymore (some handler sites simply don't load, others redirect you to the main page.)

I don't see a real feasible way currently to support automatically skipping the news thing. The news thing is completely optional, it produces no pop-ups or mandatory splash sites whatsoever.

Once you're in on the main page, going to either the Student or the Teacher platform involves a wait, because seemingly it's the main site which has the responsibility of generating a session towards the S/T facade handler, as evident by the `GUID` parameter in the hop request.
I.e. if you click on *Student page* it first goes to `/ToNeptunWeb/ToNeptunHWeb` which makes your browser wait for a little, then it plops you forward to one of the handler servers but now with a `GUID` in the request. (This `GUID` is of a so far unknown format, the length always seems to be 25 characters, and it's completely alphanumerical (I've seen letters `s`, `m`, `j`, `y`, `0`, `5`), so it's not an MD5 or SHA or anything like so. It might be a standard C# GUID but in a different (not the `xxxxxxxxx-xxxx-xxxx...`) format.)
There are some `Antiforgery` cookies attached to the session flying back and forth.

I'm not terribly experienced with JavaScript so sadly I can't go any further right now. All I can think of is that auto-login on the new login site *could* be automated or made easy (it's also a standard form that your browser can supply autofill to based on saved credentials), but the switching between the facets of the now 3 sites is not that much possible. At least not without having to wait out the wait time of this session generation.

**Comment by Kokan** [comment]
My main use case is not to see or deal with this new page, as I consider it to be a SPAM.
The delay I can live with as long as I do not have to click or be actively involved, I mean I hate the delay but probably cannot do anything with it...

The "good" news is, that the two session not connected. If you log out from the "new" page, you won't be kicked out of neptun, or if you log out of neptun you are still logged into the "new" page. But that is another story.

**Comment by solymosi** [comment]
I took a brief look into this and can confirm @whisperity's assessment.

The news site seems to be implemented using ASP.NET Core, as suggested by the presence of the anti-forgery, authentication and session tokens. This is good news because at least we don't have to deal with the stupid ViewState that's used by ASP.NET Forms-based apps (i.e. the actual Neptun UI).

Here's therefore a possible strategy for automating the login:

* Replace the login button on the news site with two buttons:
  * `Belépés a Neptun-ba`
  * `Belépés a hírekhez`
* Autofill the form and count down from 3 seconds on the `Belépés a Neptun-ba` button
* If the `Belépés a Neptun-ba` button is clicked (or the auto-login is triggered) then
  * Set a one-time flag that we need to go directly to Neptun
  * Submit the login form
  * Upon successful login clear the flag and auto-click the `Hallgatói` or `Oktatói` link, whichever appears
* If the other button is triggered, just submit the form as usual

Interestingly, the `Logout` link in the "real" Neptun doesn't actually log the user out – it merely drops them back to the news site, while still logged in. This might actually be a security issue since users may not realize that they have to log out twice 🤦‍♂️ 

All this would of course require some extra code that detects this special ELTE page and only triggers the aforementioned steps on the right site.

**Comment by whisperity** [comment]
Considering one can run multiple userscripts just fine, and that this feature was _not_ implemented _into_ Neptun but rather _bolted on top of it_, I believe it would be wiser to have a separate user script for this ELTE specific retardation, that to add the stuff (with all the "is this the ELTE stupidity homepage?" logic!) into NPU as a whole.

The code could be hosted in this repository, but should be a distinct script with a distinct installer.

**Comment by solymosi** [comment]
> Considering one can run multiple userscripts just fine, and that this feature was not implemented into Neptun but rather bolted on top of it, I believe it would be wiser to have a separate user script for this ELTE specific retardation, that to add the stuff (with all the "is this the ELTE stupidity homepage?" logic!) into NPU as a whole.

Since user scripts have isolated local storage a separate script would not have access to the already stored user credentials.  
Now that #56 is released we can add university-specific features in a clean, properly structured way.  
Let's continue the discussion in #53
