### ISSUE TITLE
Kérdőív értesítés elrejtése

### ISSUE THREAD

**Issue by ghost** [solymosi/npu#55]
Jó lenne egy olyan opció, hogy a minden bejelentkezéskor megjelenő "Önnek kitöltendő kérdőíve van" felugró ablakot el lehessen rejteni. uBlock Origin-nel megoldtam, de esetleg NPU-ba is bele lehetne írni.

**Comment by solymosi** [comment]
Unfortunately I don't have access to a Neptun account with a pending questionnaire, which makes implementing this pretty much impossible. However, if you're up for the challenge feel free to implement this as a new module and then submit a PR.

**Comment by whisperity** [comment]
Same stands for me, we do not get OMHV questionnaires anymore as PhD students.
However, as a teacher, I'd say the easiest way to make those nasty popups go away is to fill the questionnaire, and fill it proper, because we do read them (once the University gets their asses rolling and gives us the reports... which usually take a whole semester for some weird reason).
