### ISSUE TITLE
It does not work on the Neptun of the elte

### ISSUE THREAD

**Issue by Pandaniac** [solymosi/npu#64]

**Comment by whisperity** [comment]
Today is the day when the Faculty of Law is registering for their exams, and earlier today ELTE has announced that using software that "interfere with the operation of Neptun" (whatever this means) is forbidden, see image:

![image](https://user-images.githubusercontent.com/1969470/144664195-3c681340-2ea5-4ea3-93ce-b5b4d3a76e47.png)

Which is extremely funny, because the **only** feature which *COULD* be argued that is unjust or "cheating", namely the quick login manipulation, is literally *the* feature that does **NOT** work with ELTE's site ever since they announced the new homepage.

**Comment by solymosi** [comment]
LOL, I love how "subtle" they are regarding the particular piece of software they're referring to 🙄  

By the way, 2021 marks the 10th anniversary of NPU's first release 🍾 🎉 🎊

**Comment by MSZGs** [comment]
In the mean time, the page title had been set back to its original version....
